apiVersion: apps/v1
kind: Deployment
metadata:
  name: rss-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rss-api
  template:
    metadata:
      labels:
        app: rss-api
    spec:
      containers:
        - name: rss-api
          image: ghcr.io/ceddy-cedd/k3s-resume-platform/rss-api@sha256:5438b2ffcc43bf896f3db6b0a647267a3bc8c77aa401f4cfe150ded478df8777
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
