apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: rss-api
  namespace: dev
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout: 
      ref:
        branch: main
    commit:
      author:
        name: flux-bot
        email: flux@local
      messageTemplate: |
        feat: update dev rss-api image
    push:
      branch: main
  update:
    path: ./clusters/my-cluster/apps/dev/rss-api
    strategy: Setters
